version: "3.1"
services:
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    command:
      [
        mysqld,
        --default-authentication-plugin=mysql_native_password,
        --character-set-server=utf8,
        --collation-server=utf8_unicode_ci,
        --innodb_monitor_enable=all,
        --max-connections=1001
      ]
    volumes:
      - ./dump:/docker-entrypoint-initdb.d 
      - persistent:/var/lib/mysql 
    networks:
      - default
  www:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    links:
      - db
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
volumes:
  persistent: